const getUserRetentionByMonthRet = {
  ret: {
    number: [
      {
        day: '2021-10-31',
        created: 1,
        month_1: '1',
        month_2: '0',
        month_3: '',
        month_4: '',
        month_5: '',
        month_6: '',
      },
    ],
    percent: [
      {
        day: '2021-10-31',
        created: 1,
        month_1: '100.00',
        month_2: '0.00',
        month_3: '',
        month_4: '',
        month_5: '',
        month_6: '',
      },
    ],
  },
  sub_total: {
    number: {
      created: 1,
      month_1: 1,
      month_2: 0,
      month_3: '--',
      month_4: '--',
      month_5: '--',
      month_6: '--',
    },
    percent: {
      created: 1,
      month_1: '100.00',
      month_2: '0.00',
      month_3: '--',
      month_4: '--',
      month_5: '--',
      month_6: '--',
    },
  },
  total: {
    number: {
      created: '1',
      month_1: '1',
      month_2: '0',
      month_3: '--',
      month_4: '--',
      month_5: '--',
      month_6: '--',
    },
    percent: {
      created: '1',
      month_1: '100.00',
      month_2: '0.00',
      month_3: '--',
      month_4: '--',
      month_5: '--',
      month_6: '--',
    },
  },
  pagination: {
    first_result: 0,
    max_results: 20,
    total: '1',
  },
};

const getUserRetentionByWeekRet = {
  ret: {
    number: [
      {
        day: '2021-10-05',
        created: 1,
        week_1: '0',
        week_2: '0',
        week_3: '0',
        week_4: '0',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
      {
        day: '2021-10-06',
        created: 1,
        week_1: '0',
        week_2: '0',
        week_3: '0',
        week_4: '0',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
      {
        day: '2021-10-07',
        created: 4,
        week_1: '1',
        week_2: '0',
        week_3: '1',
        week_4: '0',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
    ],
    percent: [
      {
        day: '2021-10-05',
        created: 1,
        week_1: '0.00',
        week_2: '0.00',
        week_3: '0.00',
        week_4: '0.00',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
      {
        day: '2021-10-06',
        created: 1,
        week_1: '0.00',
        week_2: '0.00',
        week_3: '0.00',
        week_4: '0.00',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
      {
        day: '2021-10-07',
        created: 4,
        week_1: '25.00',
        week_2: '0.00',
        week_3: '25.00',
        week_4: '0.00',
        week_5: '',
        week_6: '',
        week_7: '',
        week_8: '',
        week_12: '',
      },
    ],
  },
  sub_total: {
    number: {
      created: 6,
      week_1: 1,
      week_2: 0,
      week_3: 1,
      week_4: 0,
      week_5: '--',
      week_6: '--',
      week_7: '--',
      week_8: '--',
      week_12: '--',
    },
    percent: {
      created: 6,
      week_1: '16.66',
      week_2: '0.00',
      week_3: '16.66',
      week_4: '0.00',
      week_5: '--',
      week_6: '--',
      week_7: '--',
      week_8: '--',
      week_12: '--',
    },
  },
  total: {
    number: {
      created: '6',
      week_1: '1',
      week_2: '0',
      week_3: '1',
      week_4: '0',
      week_5: '--',
      week_6: '--',
      week_7: '--',
      week_8: '--',
      week_12: '--',
    },
    percent: {
      created: '6',
      week_1: '16.66',
      week_2: '0.00',
      week_3: '16.66',
      week_4: '0.00',
      week_5: '--',
      week_6: '--',
      week_7: '--',
      week_8: '--',
      week_12: '--',
    },
  },
  pagination: {
    first_result: 0,
    max_results: 20,
    total: '3',
  },
};

const getUserRetentionByDayRet = {
  ret: {
    number: [
      {
        day: '2021-10-31',
        created: 1,
        day_1: '1',
        day_2: '0',
        day_3: '0',
        day_4: '',
        day_5: '',
        day_6: '',
        day_7: '',
        day_14: '',
        day_30: '',
      },
    ],
    percent: [
      {
        day: '2021-10-31',
        created: 1,
        day_1: '100.00',
        day_2: '0.00',
        day_3: '0.00',
        day_4: '',
        day_5: '',
        day_6: '',
        day_7: '',
        day_14: '',
        day_30: '',
      },
    ],
  },
  sub_total: {
    number: {
      created: 1,
      day_1: 1,
      day_2: 0,
      day_3: 0,
      day_4: '--',
      day_5: '--',
      day_6: '--',
      day_7: '--',
      day_14: '--',
      day_30: '--',
    },
    percent: {
      created: 1,
      day_1: '100.00',
      day_2: '0.00',
      day_3: '0.00',
      day_4: '--',
      day_5: '--',
      day_6: '--',
      day_7: '--',
      day_14: '--',
      day_30: '--',
    },
  },
  total: {
    number: {
      created: '1',
      day_1: '1',
      day_2: '0',
      day_3: '0',
      day_4: '--',
      day_5: '--',
      day_6: '--',
      day_7: '--',
      day_14: '--',
      day_30: '--',
    },
    percent: {
      created: '1',
      day_1: '100.00',
      day_2: '0.00',
      day_3: '0.00',
      day_4: '--',
      day_5: '--',
      day_6: '--',
      day_7: '--',
      day_14: '--',
      day_30: '--',
    },
  },
  pagination: {
    first_result: 0,
    max_results: 20,
    total: '1',
  },
};

const getUserRetentionRet = {
  month: getUserRetentionByMonthRet,
  week: getUserRetentionByWeekRet,
  day: getUserRetentionByDayRet,
};

const ret = 1;

export {
  getUserRetentionRet,
  ret,
};
